version: '3.3'
services:
  web:
    build: ../spring-music
    image: spring-music:1
    ports:
      - 8080:8080
    networks: # Define netwroks per service / role
     - fe_layer
     - db_layer        
  db_mysql:
    image: wangxian/alpine-mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=music
    ports:
      - 3302:3306
    networks:
      - db_layer

networks: # custome configuration per network defined
  db_layer:
    driver: bridge
  fe_layer:
    driver: bridge
